version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app/project:/app
    container_name: django
    networks:
      - network

#   nginx:
#     image: 'nginx:1.23.3-alpine'
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z
#     depends_on:
#       - django
#     restart: unless-stopped
#     ports:
#       - 8888:80
#     container_name: nginx
#     networks:
#       - network

# networks:
#   network:
#     driver: bridge
